#-------------------------------
# General Site Settings
title: Mark Brörkens - Projects
logo: logo.svg # You can add own logo.
description: Mark Brörkens - Projects
image: 01.jpg


#-------------------------------
# Author Settings
author:
  name: Mark Brörkens
  image: 01.jpg
  say-hello: Hello, I’m <strong>Mark Brörkens</strong>
  bio: Solution Architect, Daddy, Loves self driving vehicles


#-------------------------------
# Contact links
twitter: https://twitter.com/MarkBroerkens # Add your Twitter handle
linkedin: https://www.linkedin.com/in/markbroerkens/
xing: https://www.xing.com/profile/Mark_Broerkens 
github: https://github.com/MarkBroerkens
facebook: https://www.facebook.com/mark.broerkens
medium: https://medium.com/@markbroerkens


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
# instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
# instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: UA-19672772-2 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
# mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
